using Survey.Application.Models;

namespace Survey.Application.Services;

public interface ISurveyAdministrationService
{
	Task<SiteSettingsEditModel> GetSiteSettingsAsync(CancellationToken cancellationToken = default);
	Task SaveSiteSettingsAsync(SiteSettingsEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<CountryListItem>> GetCountriesAsync(string? search = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetStateProvinceSelectOptionsAsync(int? countryId, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetCountySelectOptionsAsync(int? stateProvinceId, CancellationToken cancellationToken = default);
	Task<CountryEditModel> GetCountryAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveCountryAsync(CountryEditModel model, CancellationToken cancellationToken = default);
	Task<GeographyImportResultModel> ImportCountriesAsync(CountryImportModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<StateProvinceListItem>> GetStateProvincesAsync(int? countryId = null, string? search = null, CancellationToken cancellationToken = default);
	Task<StateProvinceEditModel> GetStateProvinceAsync(int? id, int? countryId, CancellationToken cancellationToken = default);
	Task<int> SaveStateProvinceAsync(StateProvinceEditModel model, CancellationToken cancellationToken = default);
	Task<GeographyImportResultModel> ImportStateProvincesAsync(StateProvinceImportModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<CountyListItem>> GetCountiesAsync(int? stateProvinceId = null, string? search = null, CancellationToken cancellationToken = default);
	Task<CountyEditModel> GetCountyAsync(int? id, int? stateProvinceId, CancellationToken cancellationToken = default);
	Task<int> SaveCountyAsync(CountyEditModel model, CancellationToken cancellationToken = default);
	Task<GeographyImportResultModel> ImportCountiesAsync(CountyImportModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<PostalAddressListItem>> GetPostalAddressesAsync(string? search = null, int? countyId = null, CancellationToken cancellationToken = default);
	Task<PostalAddressEditModel> GetPostalAddressAsync(int? id, CancellationToken cancellationToken = default);
	Task<PostalAddressReferenceViewModel> GetPostalAddressReferencesAsync(int id, CancellationToken cancellationToken = default);
	Task<int> SavePostalAddressAsync(PostalAddressEditModel model, CancellationToken cancellationToken = default);
	Task<GeographyImportResultModel> ImportPostalAddressesAsync(PostalAddressImportModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveyDefinitionListItem>> GetSurveyDefinitionsAsync(bool archivedOnly = false, CancellationToken cancellationToken = default);
	Task<SurveyDefinitionEditModel> GetSurveyDefinitionAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveSurveyDefinitionAsync(SurveyDefinitionEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveyVersionListItem>> GetSurveyVersionsAsync(int? surveyDefinitionId, bool archivedOnly = false, CancellationToken cancellationToken = default);
	Task<SurveyVersionEditModel> GetSurveyVersionAsync(int? id, int? surveyDefinitionId, CancellationToken cancellationToken = default);
	Task<int> SaveSurveyVersionAsync(SurveyVersionEditModel model, CancellationToken cancellationToken = default);
	Task<int> CloneSurveyVersionAsync(int surveyVersionId, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveySectionListItem>> GetSurveySectionsAsync(int surveyVersionId, CancellationToken cancellationToken = default);
	Task<SurveySectionEditModel> GetSurveySectionAsync(int? id, int? surveyVersionId, CancellationToken cancellationToken = default);
	Task<int> SaveSurveySectionAsync(SurveySectionEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveyQuestionListItem>> GetSurveyQuestionsAsync(int surveySectionId, CancellationToken cancellationToken = default);
	Task<SurveyQuestionEditModel> GetSurveyQuestionAsync(int? id, int? surveySectionId, CancellationToken cancellationToken = default);
	Task<int> SaveSurveyQuestionAsync(SurveyQuestionEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<QuestionOptionListItem>> GetQuestionOptionsAsync(int surveyQuestionId, CancellationToken cancellationToken = default);
	Task<QuestionOptionEditModel> GetQuestionOptionAsync(int? id, int? surveyQuestionId, CancellationToken cancellationToken = default);
	Task<int> SaveQuestionOptionAsync(QuestionOptionEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<AreaListItem>> GetAreasAsync(int? countyId = null, CancellationToken cancellationToken = default);
	Task<AreaEditModel> GetAreaAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveAreaAsync(AreaEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<ZipCountyMappingListItem>> GetZipCountyMappingsAsync(string? search = null, CancellationToken cancellationToken = default);
	Task<ZipCountyMappingEditModel> GetZipCountyMappingAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveZipCountyMappingAsync(ZipCountyMappingEditModel model, CancellationToken cancellationToken = default);
	Task<ZipCountyImportResultModel> ImportZipCountyMappingsAsync(ZipCountyImportModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<GoalListItem>> GetGoalsAsync(string? userId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<DashboardFavoriteGoalItem>> GetDashboardFavoriteGoalsAsync(string userId, CancellationToken cancellationToken = default);
	Task ToggleFavoriteGoalAsync(int goalId, string userId, CancellationToken cancellationToken = default);
	Task<GoalEditModel> GetGoalAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveGoalAsync(GoalEditModel model, CancellationToken cancellationToken = default);
	Task<ReportingOverviewModel> GetReportingOverviewAsync(CancellationToken cancellationToken = default);
	Task<IReadOnlyList<PersonListItem>> GetPeopleAsync(CancellationToken cancellationToken = default);
	Task<PersonEditModel> GetPersonAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SavePersonAsync(PersonEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetLocationSelectOptionsAsync(int? personId, int? includeLocationId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetLocationPhoneSelectOptionsAsync(int? locationId, int? includePhoneId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetLocationEmailSelectOptionsAsync(int? locationId, int? includeEmailId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<LocationListItem>> GetLocationsAsync(int? personId = null, CancellationToken cancellationToken = default);
	Task<LocationEditModel> GetLocationAsync(int? id, int? personId, CancellationToken cancellationToken = default);
	Task<int> SaveLocationAsync(LocationEditModel model, CancellationToken cancellationToken = default);
	Task DeleteLocationAsync(int id, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveyAssignmentListItem>> GetAssignmentsAsync(int? personId = null, bool archivedOnly = false, string? statusFilter = null, CancellationToken cancellationToken = default);
	Task<SurveyAssignmentEditModel> GetAssignmentAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveAssignmentAsync(SurveyAssignmentEditModel model, string? createdByUserId, CancellationToken cancellationToken = default);
	Task SetAssignmentArchivedAsync(int id, bool isArchived, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveyResponseListItem>> GetResponsesAsync(CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SurveyResponseListItem>> GetUnmappedResponsesAsync(string postalCode, CancellationToken cancellationToken = default);
	Task<SurveyResponseDetailModel?> GetResponseAsync(int id, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<EmployeeListItem>> GetEmployeesAsync(string? search = null, CancellationToken cancellationToken = default);
	Task<EmployeeEditModel> GetEmployeeAsync(string? id, CancellationToken cancellationToken = default);
	Task<string> SaveEmployeeAsync(EmployeeEditModel model, CancellationToken cancellationToken = default);
}
