using Survey.Application.Models;

namespace Survey.Application.Services;

public interface ITenantAdministrationService
{
	Task<SiteSettingsEditModel> GetSiteSettingsAsync(CancellationToken cancellationToken = default);
	Task SaveSiteSettingsAsync(SiteSettingsEditModel model, CancellationToken cancellationToken = default);
	Task<TenantGeographyVisibilityEditModel> GetTenantGeographyVisibilityAsync(CancellationToken cancellationToken = default);
	Task SaveTenantGeographyVisibilityAsync(TenantGeographyVisibilityEditModel model, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetTenantStateProvinceSelectOptionsAsync(int? countryId, int? includeStateProvinceId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetTenantCountySelectOptionsAsync(int? stateProvinceId, int? includeCountyId = null, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveyDefinitionListItem>> GetSurveyDefinitionsAsync(PagedQuery request, bool archivedOnly = false, CancellationToken cancellationToken = default);
	Task<SurveyDefinitionEditModel> GetSurveyDefinitionAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveSurveyDefinitionAsync(SurveyDefinitionEditModel model, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveyVersionListItem>> GetSurveyVersionsAsync(PagedQuery request, int? surveyDefinitionId, bool archivedOnly = false, CancellationToken cancellationToken = default);
	Task<SurveyVersionEditModel> GetSurveyVersionAsync(int? id, int? surveyDefinitionId, CancellationToken cancellationToken = default);
	Task<int> SaveSurveyVersionAsync(SurveyVersionEditModel model, CancellationToken cancellationToken = default);
	Task<int> CloneSurveyVersionAsync(int surveyVersionId, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveySectionListItem>> GetSurveySectionsAsync(PagedQuery request, int surveyVersionId, CancellationToken cancellationToken = default);
	Task<SurveySectionEditModel> GetSurveySectionAsync(int? id, int? surveyVersionId, CancellationToken cancellationToken = default);
	Task<int> SaveSurveySectionAsync(SurveySectionEditModel model, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveyQuestionListItem>> GetSurveyQuestionsAsync(PagedQuery request, int surveySectionId, CancellationToken cancellationToken = default);
	Task<SurveyQuestionEditModel> GetSurveyQuestionAsync(int? id, int? surveySectionId, CancellationToken cancellationToken = default);
	Task<int> SaveSurveyQuestionAsync(SurveyQuestionEditModel model, CancellationToken cancellationToken = default);
	Task<PagedResult<QuestionOptionListItem>> GetQuestionOptionsAsync(PagedQuery request, int surveyQuestionId, CancellationToken cancellationToken = default);
	Task<QuestionOptionEditModel> GetQuestionOptionAsync(int? id, int? surveyQuestionId, CancellationToken cancellationToken = default);
	Task<int> SaveQuestionOptionAsync(QuestionOptionEditModel model, CancellationToken cancellationToken = default);
	Task<PagedResult<AreaListItem>> GetAreasAsync(PagedQuery request, int? countyId = null, CancellationToken cancellationToken = default);
	Task<AreaEditModel> GetAreaAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveAreaAsync(AreaEditModel model, CancellationToken cancellationToken = default);
	Task<PagedResult<GoalListItem>> GetGoalsAsync(PagedQuery request, string? userId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<DashboardFavoriteGoalItem>> GetDashboardFavoriteGoalsAsync(string userId, CancellationToken cancellationToken = default);
	Task ToggleFavoriteGoalAsync(int goalId, string userId, CancellationToken cancellationToken = default);
	Task<GoalEditModel> GetGoalAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveGoalAsync(GoalEditModel model, CancellationToken cancellationToken = default);
	Task<ReportingOverviewModel> GetReportingOverviewAsync(CancellationToken cancellationToken = default);
	Task<PagedResult<PersonListItem>> GetPeopleAsync(PagedQuery request, bool archivedOnly = false, CancellationToken cancellationToken = default);
	Task<PersonEditModel> GetPersonAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SavePersonAsync(PersonEditModel model, CancellationToken cancellationToken = default);
	Task SetPersonArchivedAsync(int id, bool isArchived, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetLocationSelectOptionsAsync(int? personId, int? includeLocationId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetLocationPhoneSelectOptionsAsync(int? locationId, int? includePhoneId = null, CancellationToken cancellationToken = default);
	Task<IReadOnlyList<SelectOption>> GetLocationEmailSelectOptionsAsync(int? locationId, int? includeEmailId = null, CancellationToken cancellationToken = default);
	Task<PagedResult<LocationListItem>> GetLocationsAsync(PagedQuery request, int? personId = null, CancellationToken cancellationToken = default);
	Task<LocationEditModel> GetLocationAsync(int? id, int? personId, CancellationToken cancellationToken = default);
	Task<int> SaveLocationAsync(LocationEditModel model, CancellationToken cancellationToken = default);
	Task DeleteLocationAsync(int id, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveyAssignmentListItem>> GetAssignmentsAsync(PagedQuery request, int? personId = null, bool archivedOnly = false, string? statusFilter = null, CancellationToken cancellationToken = default);
	Task<SurveyAssignmentEditModel> GetAssignmentAsync(int? id, CancellationToken cancellationToken = default);
	Task<int> SaveAssignmentAsync(SurveyAssignmentEditModel model, string? createdByUserId, CancellationToken cancellationToken = default);
	Task SetAssignmentArchivedAsync(int id, bool isArchived, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveyResponseListItem>> GetResponsesAsync(PagedQuery request, CancellationToken cancellationToken = default);
	Task<PagedResult<SurveyResponseListItem>> GetUnmappedResponsesAsync(PagedQuery request, string postalCode, CancellationToken cancellationToken = default);
	Task<SurveyResponseDetailModel?> GetResponseAsync(int id, CancellationToken cancellationToken = default);
	Task<PagedResult<TenantUserListItem>> GetTenantUsersAsync(PagedQuery request, string? search = null, CancellationToken cancellationToken = default);
	Task<TenantUserEditModel> GetTenantUserAsync(int membershipId, CancellationToken cancellationToken = default);
	Task<int> SaveTenantUserAsync(TenantUserEditModel model, CancellationToken cancellationToken = default);
	Task RemoveTenantUserAsync(int membershipId, CancellationToken cancellationToken = default);
	Task<TenantInvitationCreateResultModel> CreateTenantInvitationAsync(TenantUserInviteModel model, CancellationToken cancellationToken = default);
	Task<PagedResult<TenantInvitationListItem>> GetTenantInvitationsAsync(PagedQuery request, bool includeHistory = true, CancellationToken cancellationToken = default);
	Task<TenantInvitationCreateResultModel> ReissueTenantInvitationAsync(int invitationId, CancellationToken cancellationToken = default);
	Task RevokeTenantInvitationAsync(int invitationId, CancellationToken cancellationToken = default);
	Task<TenantInvitationAcceptanceContextModel> GetTenantInvitationAcceptanceAsync(string token, CancellationToken cancellationToken = default);
	Task<string> AcceptTenantInvitationForExistingUserAsync(string token, string userId, CancellationToken cancellationToken = default);
	Task<string> AcceptTenantInvitationForNewUserAsync(TenantInvitationRegistrationModel model, CancellationToken cancellationToken = default);
	Task<TenantSearchResultModel> SearchTenantAsync(string query, CancellationToken cancellationToken = default);
}
